import Foundation
import UIKit

enum SymbolExportError: LocalizedError {
    case unavailable(String)
    case renderingFailed(String)

    var errorDescription: String? {
        switch self {
        case .unavailable(let name): "이 기기에서 \(name) 심볼을 사용할 수 없습니다."
        case .renderingFailed(let name): "\(name) 심볼을 렌더링하지 못했습니다."
        }
    }
}

enum SymbolExporter {
    static func data(for item: SymbolItem, settings: ExportSettings) throws -> Data {
        let png = try pngData(for: item, settings: settings)
        switch settings.format {
        case .png:
            return png
        case .svg:
            return compatibleSVG(for: item, settings: settings, pngData: png)
        }
    }

    static func zipData(for items: [SymbolItem], settings: ExportSettings) throws -> Data {
        var entries = try items.map { item in
            ZipArchiveWriter.Entry(
                path: "symbols/\(safeFilename(item.name)).\(settings.format.fileExtension)",
                data: try data(for: item, settings: settings)
            )
        }

        let manifest = Manifest(
            app: "SymbolShelf",
            exportedAt: ISO8601DateFormatter().string(from: Date()),
            format: settings.format.rawValue,
            size: settings.size,
            weight: settings.weight.rawValue,
            background: settings.background.rawValue,
            tint: settings.tint.rawValue,
            vectorPathsIncluded: false,
            symbols: items.map(\.name)
        )
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys, .withoutEscapingSlashes]
        entries.append(.init(path: "manifest.json", data: try encoder.encode(manifest)))
        entries.append(.init(path: "README.txt", data: Data(archiveNotice.utf8)))
        return ZipArchiveWriter.archive(entries: entries)
    }

    static func filename(for item: SymbolItem, settings: ExportSettings) -> String {
        "\(safeFilename(item.name))-\(settings.size).\(settings.format.fileExtension)"
    }

    private static func pngData(for item: SymbolItem, settings: ExportSettings) throws -> Data {
        let dimension = CGFloat(settings.size)
        let configuration = UIImage.SymbolConfiguration(
            pointSize: dimension * 0.68,
            weight: settings.weight.uiWeight,
            scale: .large
        )
        guard let base = UIImage(systemName: item.name, withConfiguration: configuration) else {
            throw SymbolExportError.unavailable(item.name)
        }

        let image = base.withTintColor(settings.tint.uiColor, renderingMode: .alwaysOriginal)
        let format = UIGraphicsImageRendererFormat()
        format.scale = 1
        format.opaque = settings.background != .transparent
        let renderer = UIGraphicsImageRenderer(size: CGSize(width: dimension, height: dimension), format: format)
        let rendered = renderer.image { context in
            switch settings.background {
            case .transparent:
                context.cgContext.clear(CGRect(x: 0, y: 0, width: dimension, height: dimension))
            case .white:
                UIColor.white.setFill()
                context.fill(CGRect(x: 0, y: 0, width: dimension, height: dimension))
            case .black:
                UIColor.black.setFill()
                context.fill(CGRect(x: 0, y: 0, width: dimension, height: dimension))
            }

            let maxSide = dimension * 0.72
            let scale = min(maxSide / image.size.width, maxSide / image.size.height)
            let target = CGSize(width: image.size.width * scale, height: image.size.height * scale)
            let origin = CGPoint(x: (dimension - target.width) / 2, y: (dimension - target.height) / 2)
            image.draw(in: CGRect(origin: origin, size: target))
        }

        guard let data = rendered.pngData() else {
            throw SymbolExportError.renderingFailed(item.name)
        }
        return data
    }

    private static func compatibleSVG(for item: SymbolItem, settings: ExportSettings, pngData: Data) -> Data {
        let encoded = pngData.base64EncodedString()
        let xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" width="\(settings.size)" height="\(settings.size)" viewBox="0 0 \(settings.size) \(settings.size)" role="img" aria-label="\(item.name)">
          <title>\(item.name)</title>
          <metadata>Generated by SymbolShelf. Raster SF Symbol embedded for API and license compatibility; no vector paths included.</metadata>
          <image width="\(settings.size)" height="\(settings.size)" href="data:image/png;base64,\(encoded)"/>
        </svg>
        """
        return Data(xml.utf8)
    }

    private static func safeFilename(_ name: String) -> String {
        name.replacingOccurrences(of: "/", with: "-")
    }

    private static let archiveNotice = """
    SymbolShelf export

    SF Symbols are Apple platform assets. Use exported files according to Apple's SF Symbols license and Human Interface Guidelines.
    SVG files in this archive embed a PNG image and do not contain original vector paths.
    """

    private struct Manifest: Encodable {
        let app: String
        let exportedAt: String
        let format: String
        let size: Int
        let weight: String
        let background: String
        let tint: String
        let vectorPathsIncluded: Bool
        let symbols: [String]
    }
}
