import Foundation
import UIKit
import Vision

enum SymbolVectorizer {
    static func svgData(for item: SymbolItem, settings: ExportSettings) throws -> Data {
        let dimension: CGFloat = 1024
        let configuration = UIImage.SymbolConfiguration(
            pointSize: dimension * 0.68,
            weight: settings.weight.uiWeight,
            scale: .large
        )
        guard let base = UIImage(systemName: item.name, withConfiguration: configuration) else {
            throw SymbolExportError.unavailable(item.name)
        }

        let format = UIGraphicsImageRendererFormat()
        format.scale = 1
        format.opaque = true
        let renderer = UIGraphicsImageRenderer(
            size: CGSize(width: dimension, height: dimension),
            format: format
        )
        let mask = renderer.image { context in
            UIColor.white.setFill()
            context.fill(CGRect(x: 0, y: 0, width: dimension, height: dimension))

            let image = base.withTintColor(.black, renderingMode: .alwaysOriginal)
            let maxSide = dimension * 0.72
            let scale = min(maxSide / image.size.width, maxSide / image.size.height)
            let target = CGSize(width: image.size.width * scale, height: image.size.height * scale)
            let origin = CGPoint(x: (dimension - target.width) / 2, y: (dimension - target.height) / 2)
            image.draw(in: CGRect(origin: origin, size: target))
        }

        guard let cgImage = mask.cgImage else {
            throw SymbolExportError.renderingFailed(item.name)
        }

        let request = VNDetectContoursRequest()
        request.contrastAdjustment = 1
        request.detectsDarkOnLight = true
        request.maximumImageDimension = Int(dimension)
        let handler = VNImageRequestHandler(cgImage: cgImage, orientation: .up, options: [:])
        try handler.perform([request])

        guard let observation = request.results?.first else {
            throw SymbolExportError.renderingFailed(item.name)
        }

        let pathData = svgPathData(from: observation.normalizedPath, dimension: dimension)
        guard !pathData.isEmpty else {
            throw SymbolExportError.renderingFailed(item.name)
        }

        let background = backgroundElement(settings.background, dimension: Int(dimension))
        let fill = svgColor(settings.tint.uiColor)
        let xml = """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" role="img" aria-label="\(item.name)">
          <title>\(item.name)</title>
          <metadata>Generated by SymbolShelf using automatic contour tracing. Paths are approximations and do not contain Apple's original SF Symbol vector data.</metadata>
        \(background)  <path d="\(pathData)" fill="\(fill)" fill-rule="evenodd"/>
        </svg>
        """
        return Data(xml.utf8)
    }

    private static func svgPathData(from path: CGPath, dimension: CGFloat) -> String {
        var commands: [String] = []
        path.applyWithBlock { elementPointer in
            let element = elementPointer.pointee
            let points = element.points
            switch element.type {
            case .moveToPoint:
                commands.append("M\(point(points[0], dimension: dimension))")
            case .addLineToPoint:
                commands.append("L\(point(points[0], dimension: dimension))")
            case .addQuadCurveToPoint:
                commands.append("Q\(point(points[0], dimension: dimension)) \(point(points[1], dimension: dimension))")
            case .addCurveToPoint:
                commands.append("C\(point(points[0], dimension: dimension)) \(point(points[1], dimension: dimension)) \(point(points[2], dimension: dimension))")
            case .closeSubpath:
                commands.append("Z")
            @unknown default:
                break
            }
        }
        return commands.joined(separator: " ")
    }

    private static func point(_ point: CGPoint, dimension: CGFloat) -> String {
        let x = point.x * dimension
        let y = (1 - point.y) * dimension
        return "\(number(x)) \(number(y))"
    }

    private static func number(_ value: CGFloat) -> String {
        String(format: "%.2f", locale: Locale(identifier: "en_US_POSIX"), Double(value))
    }

    private static func backgroundElement(_ background: ExportBackground, dimension: Int) -> String {
        switch background {
        case .transparent:
            return ""
        case .white:
            return "  <rect width=\"\(dimension)\" height=\"\(dimension)\" fill=\"#FFFFFF\"/>\n"
        case .black:
            return "  <rect width=\"\(dimension)\" height=\"\(dimension)\" fill=\"#000000\"/>\n"
        }
    }

    private static func svgColor(_ color: UIColor) -> String {
        let resolved = color.resolvedColor(with: UITraitCollection(userInterfaceStyle: .light))
        var red: CGFloat = 0
        var green: CGFloat = 0
        var blue: CGFloat = 0
        var alpha: CGFloat = 0
        guard resolved.getRed(&red, green: &green, blue: &blue, alpha: &alpha) else {
            return "#000000"
        }
        return String(
            format: "#%02X%02X%02X",
            Int(round(red * 255)),
            Int(round(green * 255)),
            Int(round(blue * 255))
        )
    }
}
